### ISSUE TITLE
since a few days not working

### ISSUE THREAD

**Issue by Poppycat** [sgruendel/alexa-radio-paradise#1] opened 2019-01-09 08:25 UTC
asking alexa:
open paradise playlist
result (always)
I ask Bill
few seconds later
bill is not there
happens on all 3 devices.
anything I do wrong? anything I can check?

**Comment by sgruendel** [comment] 2019-01-09 08:35
This is caused by the new RP site. It's already fixed in version 2.2.x which I submitted on Dec 14th as updated skill, unfortunately it failed certification because Amazon said I need to "provide documentation demonstrating that you have the right to use the music content within your skill." ...

I'm in contact with their developer support and have already submitted the skill again as requested on Jan 3rd, so I hope it goes live in the next couple of days.

**Closed by sgruendel** 2019-01-09 08:35 UTC
